### ISSUE TITLE
Binary XML file line #0: Binary XML file line #0: Error inflating class com.ashokvarma.bottomnavigation.BadgeTextView

### ISSUE THREAD

**Issue by whb7762300** [Ashok-Varma/BottomNavigation#158]
when i use compilesdk 26,it will crash: Binary XML file line #0: Binary XML file line #0: Error inflating class com.ashokvarma.bottomnavigation.BadgeTextView
but it's no problem at compilesdk 25

**Comment by Ashok-Varma** [comment]
u might be using different versions of support-libraries. Latest version of library uses 27.0.2 please update your libraries and check

**Comment by whb7762300** [comment]
@Ashok-Varma thanks,I compile support_lib 26.1.0,but I still find support_lib 27.0.2 in external libraries.I don't know why(maybe about glide4.4.0),but thanks a lot

**Comment by Ashok-Varma** [comment]
if you are using latest version of this library then you need to compile with 27 and all other libraries you use also should use in 27 support_lib.

because gradle will automatically replace all support libraries with which ever is highest. if you are using 10 libraries it will pick the highest support library of all of them and apply it to all 10 libraries. so one needs to maintain all libraries in the project at same support library to avoid issues.

26,26.0.1, 26.0.2 ..etc wont create much problem because there wont be breaking changes in minor updates. But one should make sure there are no two different versions used by libraries in one's project

if you want to use 26 support library and use previous version of the library.
