### ISSUE TITLE
badges、BottomBarTab

### ISSUE THREAD

**Issue by hcadoid** [Ashok-Varma/BottomNavigation#88]
1.simple circle badges and don't use badges with text,Resize the circle，Can you do that?
2.Bottom Bar After initialization, you can modify the style of Bottom Bar Tab
Thank you。

**Comment by Ashok-Varma** [comment]
1. No, for personal customizations you can fork repo and change the things. Changing is pretty easy because the badge is separate entity by itself.
2. BottomBar can't change style after initialization. That is not recommended. But if you want you can setStyle clear and re-initialize bottom bar if you want.
